### PR TITLE
fix: Wait for EOF or ReadWaitTime before starting initial search

### LINKED ISSUE #765: Bug: Intermittent search failure when using ov with man
Thanks for writing this great pager, I really like it! I'm having a problem when using it with `man`, however. Using the following command:

```
man --pager="ov --pattern \"^GUIDES\" --regexp-search" git
```

Ov sometimes reports `git(1):search:not found:^GUIDES` while at other times the search works and the man page opens at the `GUIDES` section.

Here are the versions I'm usuing:

```
man 2.13.0
ov version v0.40.0 rev:5c3ece8
```
 My OS:

```
> lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        25.0.0
Codename:       Zetar
> uname -srvpio
Linux 6.1.131-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Mar 13 15:02:58 UTC 2025 unknown unknown GNU/Linux
```

### PR DESCRIPTION
**Pull request by noborus**
Addressed an intermittent search failure when using `ov` with `man`. 
The initial search now waits for EOF or the configured `ReadWaitTime` before starting, ensuring proper handling of input streams. 

fixed #765

### CODE REVIEW

File: oviewer/document.go [hunk 1]
```diff
@@ -468,6 +469,27 @@ func (m *Document) WaitEOF() {
...
+		doneCh <- struct{}{}
+	}()
+
+	timeoutCh := time.After(time.Duration(timeout) * time.Millisecond)
+	select {
+	case <-doneCh:
+	case <-timeoutCh:
+		log.Println("WaitEOFWithTimeout timed out")
+	}
+}
```
Comment (ccoVeille) [inline oviewer/document.go:491]:
```suggestion
func (m *Document) WaitEOFWithTimeout(timeout time.Duration) {
	if m.BufEOF() {
		return
	}

	doneCh := make(chan struct{})
	go func() {
		m.cond.L.Lock()
		defer m.cond.L.Unlock()
		m.cond.Wait()
		doneCh <- struct{}{}
	}()

	select {
	case <-doneCh:
	case <-time.After(timeout):
		log.Println("WaitEOFWithTimeout timed out")
	}
}
```

**Review by ccoVeille — CHANGES_REQUESTED** [review]

File: oviewer/document.go (hunk 1 above)
Comment (noborus) [reply oviewer/document.go:491]: Thank you. As you say, time.Duration seems to be better.

**Review by ccoVeille — APPROVED** [review]
